name: careflow_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  provider: ^6.1.4
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  go_router: ^15.1.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  dio: ^5.8.0+1
  flutter_dotenv: ^5.0.2
  flutter_markdown: ^0.6.18
  path: ^1.9.1
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
